---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require: []
domains: []
reporters: []
formatter:
  rubocop:
    extra_args:
      - '--lint'
require_paths: []
plugins: []
max_files: 5000
