#!/bin/sh
#
# Usage:
#
#    sh install-linux.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME.
#
#    env VERBOSE=1 sh install-linux.sh
#
# DO NOT EDIT THIS FILE
#
# Generated by rcm(7) with portable paths. To regenerate on macOS:
#
#   env RCRC=./rcrc rcup -B 0 -g -t linux \
#     | sed 's|/path/to/dotfiles|$DOTFILES_DIR|g; s|/home/user|$HOME|g' \
#     > install-linux.sh
#
# Then add the DOTFILES_DIR= line below this header.
#
DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $LN -sf "$1" "$2"
}
handle_file_ln "$DOTFILES_DIR/tag-linux/config/fish/config.fish" "$HOME/.config/fish/config.fish"
handle_file_ln "$DOTFILES_DIR/config/fish/conf.d/fzf_theme.fish" "$HOME/.config/fish/conf.d/fzf_theme.fish"
handle_file_ln "$DOTFILES_DIR/config/fish/fish_plugins" "$HOME/.config/fish/fish_plugins"
handle_file_ln "$DOTFILES_DIR/config/fish/functions/fish_prompt.fish" "$HOME/.config/fish/functions/fish_prompt.fish"
handle_file_ln "$DOTFILES_DIR/config/fish/functions/fish_right_prompt.fish" "$HOME/.config/fish/functions/fish_right_prompt.fish"
handle_file_ln "$DOTFILES_DIR/config/fish/functions/g.fish" "$HOME/.config/fish/functions/g.fish"
handle_file_ln "$DOTFILES_DIR/config/fish/themes/custom.theme" "$HOME/.config/fish/themes/custom.theme"
handle_file_ln "$DOTFILES_DIR/config/ghostty/config" "$HOME/.config/ghostty/config"
handle_file_ln "$DOTFILES_DIR/config/ghostty/themes/light" "$HOME/.config/ghostty/themes/light"
handle_file_ln "$DOTFILES_DIR/config/mise/config.toml" "$HOME/.config/mise/config.toml"
handle_file_ln "$DOTFILES_DIR/config/nvim/after/ftplugin/gitcommit.lua" "$HOME/.config/nvim/after/ftplugin/gitcommit.lua"
handle_file_ln "$DOTFILES_DIR/config/nvim/after/ftplugin/go.lua" "$HOME/.config/nvim/after/ftplugin/go.lua"
handle_file_ln "$DOTFILES_DIR/config/nvim/after/ftplugin/php.lua" "$HOME/.config/nvim/after/ftplugin/php.lua"
handle_file_ln "$DOTFILES_DIR/config/nvim/after/lsp/ruby_lsp.lua" "$HOME/.config/nvim/after/lsp/ruby_lsp.lua"
handle_file_ln "$DOTFILES_DIR/config/nvim/colors/light.lua" "$HOME/.config/nvim/colors/light.lua"
handle_file_ln "$DOTFILES_DIR/config/nvim/init.lua" "$HOME/.config/nvim/init.lua"
handle_file_ln "$DOTFILES_DIR/config/nvim/lua/autocmds.lua" "$HOME/.config/nvim/lua/autocmds.lua"
handle_file_ln "$DOTFILES_DIR/config/nvim/lua/commands.lua" "$HOME/.config/nvim/lua/commands.lua"
handle_file_ln "$DOTFILES_DIR/config/nvim/lua/config.lua" "$HOME/.config/nvim/lua/config.lua"
handle_file_ln "$DOTFILES_DIR/config/nvim/lua/keymaps.lua" "$HOME/.config/nvim/lua/keymaps.lua"
handle_file_ln "$DOTFILES_DIR/config/nvim/lua/plugins/fzf.lua" "$HOME/.config/nvim/lua/plugins/fzf.lua"
handle_file_ln "$DOTFILES_DIR/config/nvim/lua/plugins/jira.lua" "$HOME/.config/nvim/lua/plugins/jira.lua"
handle_file_ln "$DOTFILES_DIR/config/nvim/lua/theme/palette.lua" "$HOME/.config/nvim/lua/theme/palette.lua"
handle_file_ln "$DOTFILES_DIR/config/nvim/lua/theme/theme.lua" "$HOME/.config/nvim/lua/theme/theme.lua"
handle_file_ln "$DOTFILES_DIR/config/nvim/nvim-pack-lock.json" "$HOME/.config/nvim/nvim-pack-lock.json"
handle_file_ln "$DOTFILES_DIR/config/nvim/shipwright_build.lua" "$HOME/.config/nvim/shipwright_build.lua"
handle_file_ln "$DOTFILES_DIR/default-gems" "$HOME/.default-gems"
handle_file_ln "$DOTFILES_DIR/default-go-packages" "$HOME/.default-go-packages"
handle_file_ln "$DOTFILES_DIR/default-npm-packages" "$HOME/.default-npm-packages"
handle_file_ln "$DOTFILES_DIR/gemrc" "$HOME/.gemrc"
handle_file_ln "$DOTFILES_DIR/gitattributes" "$HOME/.gitattributes"
handle_file_ln "$DOTFILES_DIR/gitconfig" "$HOME/.gitconfig"
handle_file_ln "$DOTFILES_DIR/gitignore" "$HOME/.gitignore"
handle_file_ln "$DOTFILES_DIR/hushlogin" "$HOME/.hushlogin"
handle_file_ln "$DOTFILES_DIR/irbrc" "$HOME/.irbrc"
handle_file_ln "$DOTFILES_DIR/rcrc" "$HOME/.rcrc"
