local colors = {
Normal = {fg = "#49455E"},
Function = {link = "Normal"},
Identifier = {link = "Normal"},
rubyMethodName = {link = "Normal"},
rubySymbol = {link = "Normal"},
["@variable"] = {link = "Normal"},
Boolean = {fg = "#D7837E"},
Character = {},
ColorColumn = {bg = "#F3EAE2"},
Comment = {fg = "#898494"},
SpecialComment = {link = "Comment"},
Conceal = {},
Conditional = {fg = "#B4647B"},
Constant = {fg = "#D7837E"},
CurSearch = {fg = "#FCF8F3", bg = "#EA9E34"},
Cursor = {fg = "#FCF8F3", bg = "#49455E"},
CursorColumn = {bg = "#F3EAE2"},
CursorLine = {bg = "#F3EAE2"},
Debug = {},
Delimiter = {fg = "#636076"},
DiagnosticError = {fg = "#C63958"},
DiagnosticHint = {fg = "#9B80C6"},
DiagnosticInfo = {fg = "#56949F"},
DiagnosticOk = {},
DiagnosticUnderlineError = {sp = "#C63958", underline = true},
DiagnosticUnderlineHint = {sp = "#9B80C6", underline = true},
DiagnosticUnderlineInfo = {sp = "#56949F", underline = true},
DiagnosticUnderlineOk = {underline = true},
DiagnosticUnderlineWarn = {sp = "#EA9E34", underline = true},
DiagnosticWarn = {fg = "#EA9E34"},
DiffAdd = {bg = "#DCE5E3"},
diffAdded = {link = "DiffAdd"},
DiffChange = {bg = "#E9E1EA"},
diffChanged = {link = "DiffChange"},
DiffDelete = {bg = "#EDD9DA"},
diffRemoved = {link = "DiffDelete"},
DiffText = {bg = "#F3EAE2"},
Directory = {fg = "#56949F", bold = true},
Error = {fg = "#B4647B"},
ErrorMsg = {fg = "#C63958"},
Float = {},
Folded = {fg = "#636076", bg = "#F3EAE2"},
Ignore = {},
Include = {},
Keyword = {fg = "#4468A7"},
Label = {fg = "#D7837E"},
LineNr = {fg = "#898494"},
MatchParen = {fg = "#296B85", bg = "#C6D4D7"},
ModeMsg = {fg = "#636076"},
MsgArea = {link = "ModeMsg"},
MsgSeparator = {link = "ModeMsg"},
MoreMsg = {fg = "#9B80C6"},
NonText = {fg = "#CECACD"},
NormalFloat = {},
Number = {},
Operator = {},
Pmenu = {fg = "#636076"},
PmenuMatch = {fg = "#EA9E34", bold = true},
PmenuSbar = {bg = "#F3EAE2"},
PmenuSel = {bg = "#E3DFDE"},
PmenuThumb = {bg = "#898494"},
PreCondit = {},
PreProc = {fg = "#296B85"},
Question = {fg = "#636076"},
QuickFixLine = {fg = "#56949F"},
Repeat = {fg = "#B4647B"},
Search = {fg = "#49455E", bg = "#F8E6CE"},
SpecialChar = {link = "Special"},
SpellBad = {sp = "#C63958", undercurl = true},
SpellCap = {sp = "#EA9E34", undercurl = true},
SpellLocal = {undercurl = true},
SpellRare = {sp = "#9B80C6", undercurl = true},
Statement = {fg = "#9B80C6"},
StatusLine = {fg = "#636076", bg = "#F3EAE2"},
StatusLineNC = {fg = "#898494", bg = "#F7EFE9"},
StorageClass = {},
String = {fg = "#296B85"},
Special = {link = "String"},
Structure = {},
Tag = {},
Title = {fg = "#56949F", bold = true},
Todo = {fg = "#D7837E", bg = "#F5E0DB"},
Type = {fg = "#B4583C"},
Typedef = {},
Underlined = {underline = true},
Visual = {bg = "#E3DFDE"},
WarningMsg = {fg = "#EA9E34"},
Winseparator = {},
["llama_hl_hint"] = {fg = "#898494", italic = true},
["llama_hl_info"] = {fg = "#56949F"},
["@lsp.type.method"] = {},
}
vim.opt.background = "light"
vim.cmd("highlight clear")
vim.cmd("syntax reset")
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
