#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
# trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | ripper-tags -R -L - -f "$dir/$$.tags" --tag-relative=FALSE
mv "$dir/$$.tags" "$dir/tags"
