[tools]
bun = "latest"
"gem:ruby-lsp" = "latest"
go = "latest"
node = "lts"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
python = "3.13"
ruby = "latest"
usage = "latest"

[env]
MISE_DEFAULT_CONFIG_FILENAME = '.mise.local.toml'

[settings]
experimental = true
